### ISSUE TITLE
GeneExpressionExplorer is broken

### ISSUE THREAD

**Issue by ldash** [RGLab/LabKeyModules#21]
@SRenan 
GEE is broken on Production - I'm assuming it has been, ever since you left, because none of us touched it or the data really: https://www.immunespace.org/GeneExpressionExplorer/Studies/begin.view
Time point: 0 hours (1 cohort)
Cohorts: Study group 2 2009-2010 Fluzone (SDY180) <- the only one there
Genes: A1BG <- the first one
There is no filtering on the "Data Finder"

Error is:

Error in merge.data.table(data, PD, by = "biosample_accession") : Elements listed in `by` must be valid column names in x and y

Afer some investigation I can tell the following:

The resulting error on line 128 is because data does not have the `biosample_accesssion` column, though line 127 suggests it should.
The above is due to line 120, because `PD$biosample_accession` is an empty column, I mean, the whole `PD` is empty.
It is empty, because `merge(PD, HAI, by = "participant_id")` in line 117 makes it empty.
And the reason, why it's empty is that the sets of participant_id-s from the 2 data frames do not overlap.
The JOIN in line 113 reduces the number of unique PTIDs from 21 down to just 3 within HAI.

Not sure, if it's the correct approach/fix, but If we keep non-matched rows on the left by adding in line 113 `, all.x = TRUE`, then things seem to work (it appears we get the same result as if running the module from just within SDY180)

Could you, please, investigate and if the above fix is not correct, then add some extra logiс either to fix it (not sure how) or to fail gracefully with an info message?

Reproducible on test as well, of course...

**Comment by gfinak** [comment]
@ldash If you `use all.x=TRUE` you'll keep all subjects from the expression data, with corresponding NAs for those that are missing HAI data. That seems reasonable to me. They would be dropped anyway when plotting, so it should be equivalent to keeping only subjects where both types of data occur.

**Comment by ldash** [comment]
Thanks, @gfinak Not sure, if you saw Renan's comment on Slack in the IS channel about this, but he wrote: "I don't think that the suggested fix is correct because it wouldn't limit the data to peak immunogenicty. I can't check exactly how it would behave but it would likely end with multiple points per subject."

**Comment by gfinak** [comment]
Okay, it wasn't clear to me that the HAI data was limited to a specific time point.

Greg Finak

**Comment by ldash** [comment]
Addressed by 28b20675043077cfcd8894e8a6369b0bdbad11a7
