### ISSUE TITLE
immport.schema mbaa analyte fix review

### ISSUE THREAD

**Issue by SRenan** [RGLab/LabKeyModules#4]
@mbellew 
Can you review the changes I have made to the immport schema to fix the analyte column of the mbaa dataset?
SQL: 03698c3e16a49824272ce1b4f5363bb16714a217
Version and XML: eb0f450ece8730397a9184745b6f3c8625ca32bd

I have deployed it on test, reloaded the archive as well as a couple of studies that have mbaa and it looks good. I just want to make sure I didn't do anything wrong before updating production.

**Comment by labkey-matthewb** [comment]
Looks good.  It's maybe a little odd to jump to 15.00 since there's not
such release, but if this is already committed I wouldn't change it.

Matt

**Comment by SRenan** [comment]
I was worried that I may need more iterations until I get it to work. So, next change I make, I can bump the version up to 15.10?

**Comment by mbellew** [comment]
No I'd just go with 15.01.  When we're done with this round of changes, I
can make a rollup script 14.30-15.10 that contains all the changes in one
script.

**Comment by SRenan** [comment]
Okay. That's good for now. We will update production tomorrow evening.
Thank you.
